require "securerandom"

# Generated by tinfoil 0.2.20 and customized for Wardwright service installs.
# This file is a template. `mix tinfoil.homebrew` fills in version,
# URLs, and SHA256 checksums from the published release assets and
# pushes the result to the tap repo.
class Wardwright < Formula
  desc "Synthetic model policy, routing, and governance workbench"
  homepage "https://github.com/bglusman/wardwright"
  version "0.0.3"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/bglusman/wardwright/releases/download/v0.0.3/wardwright-0.0.3-aarch64-apple-darwin.tar.gz"
      sha256 "cd08ad8ac02f1071dd3aeca0a7e1bf0839ce2f8c72f86c0c1b29bab0bad27922"
    end
    on_intel do
      url "https://github.com/bglusman/wardwright/releases/download/v0.0.3/wardwright-0.0.3-x86_64-apple-darwin.tar.gz"
      sha256 "6821a1737aba4c4f979a4520cf8b065304dbe90e083178f1e2be25da250378e0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/bglusman/wardwright/releases/download/v0.0.3/wardwright-0.0.3-aarch64-unknown-linux-musl.tar.gz"
      sha256 "bf9cf6b95e2e0a27bedf38698dce12ddd27be4e82581f65280c129ae3f729bed"
    end
    on_intel do
      url "https://github.com/bglusman/wardwright/releases/download/v0.0.3/wardwright-0.0.3-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c2de578e78ba97d590e1a308b3942efa814fd04a99eb649102b7711ff87e18d4"
    end
  end

  def install
    bin.install "wardwright"
  end

  def post_install
    (etc/"wardwright").mkpath
    (var/"lib/wardwright").mkpath
    (var/"log/wardwright").mkpath

    secret_key_base = etc/"wardwright/secret_key_base"
    bind = etc/"wardwright/bind"

    secret_key_base.write("#{SecureRandom.base64(64)}\n") unless secret_key_base.exist?
    chmod 0600, secret_key_base
    bind.write("127.0.0.1:8787\n") unless bind.exist?
  end

  service do
    secret_key_base = etc/"wardwright/secret_key_base"
    bind = etc/"wardwright/bind"

    run [opt_bin/"wardwright"]
    keep_alive true
    working_dir var/"lib/wardwright"
    environment_variables(
      WARDWRIGHT_BIND: bind.exist? ? bind.read.strip : "127.0.0.1:8787",
      WARDWRIGHT_SECRET_KEY_BASE: secret_key_base.exist? ? secret_key_base.read.strip : "",
      PATH: "#{opt_bin}:#{HOMEBREW_PREFIX}/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    )
    log_path var/"log/wardwright/wardwright.log"
    error_log_path var/"log/wardwright/wardwright.log"
  end

  def caveats
    <<~EOS
      Wardwright installs as a local HTTP service bound to 127.0.0.1:8787 by default.

      Start it with:
        brew services start wardwright

      To use a different bind address or port:
        echo 127.0.0.1:8788 > #{etc}/wardwright/bind
        brew services restart wardwright

      The formula generates a stable Phoenix signing secret at:
        #{etc}/wardwright/secret_key_base

      To protect admin endpoints from non-loopback callers, set:
        WARDWRIGHT_ADMIN_TOKEN

      The packaged binary is a Burrito-wrapped BEAM release. It does not require
      Erlang, Elixir, or Gleam at runtime.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/wardwright --version")
  end
end
